# Generated by Django 5.1.1 on 2025-04-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
